import Head from "next/head";
import { DarkModeProvider } from "../providers/ThemeProvider";
import Main from "@/components/main/Main";

export default function Home() {

  return (
    <>
      <Head>
        <title>Gusholz Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <style jsx global>{`
        body {
          margin: 0;
          padding: 0;
          --white: #D9D9D9;
          --gray_light: #8C8C8C;
          --gray_medium: #737373;
          --gray_dark: #404040;
          --black: #0D0D0D
        }
      `}</style>
      <DarkModeProvider>
        <Main/>
      </DarkModeProvider>
    </>
  );
}
